### ISSUE TITLE
Notification fails silently

### ISSUE THREAD

**Issue by clear-com** [NodeBB/nodebb-plugin-pushbullet#25]
I have successfully associated an account with pushbullet in nodeBB. 

When I send a test notification, it does not display any errors but it does not send the notification either. 

What can it be ?

**Comment by ccr-chaussec** [comment]
I finally looked at the log and saw this when I press the button to test notification and nodeBB restarts

> 10 11:10 [11656] - error: TypeError: undefined is not a function
    at /home/eng/NodeBB/src/posts.js:176:12
    at try_callback (/home/eng/NodeBB/node_modules/redis/index.js:573:9)
    at RedisClient.return_reply (/home/eng/NodeBB/node_modules/redis/index.js:661:13)
    at ReplyParser.<anonymous> (/home/eng/NodeBB/node_modules/redis/index.js:309:14)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_reply (/home/eng/NodeBB/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/home/eng/NodeBB/node_modules/redis/lib/parser/javascript.js:203:22)
    at RedisClient.on_data (/home/eng/NodeBB/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/home/eng/NodeBB/node_modules/redis/index.js:91:14)
    at Socket.EventEmitter.emit (events.js:95:17)
[cluster] Child Process (11656) has exited (code: 1, signal: null)
[cluster] Spinning up another process

**Comment by pitaj** [comment]
@julianlam My notifications are also failing silently. I'm not getting *any* errors in the console, client side or server side (it looks like his error is completely unrelated). It just says "Test Notification sent" and nothing happens.

**Comment by k1ng440** [comment]
when i click test notification button, my nodebb just crashes
